w3c/json-ld-framing

- common/common.js
- index.html
- tests/frame-manifest.jsonld
- tests/frame/0052-frame.jsonld
- tests/frame/0052-in.jsonld
- tests/frame/0053-frame.jsonld
- tests/frame/0053-in.jsonld
to require that values of `@id` or `@type` within a frame are an empty dictionary or are all valid IRIs.
Adds tests.
Fixes #9.
cc/ @vcharpenay
> Update requirements for @id and @type in a frame

- common/algorithm-terms.html
- common/terms.html
- index.html
* Make definition identifiers singular, and use automatic term pluralization.
* Update previous published version.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/25.html" title="Last updated on Oct 12, 2018, 9:24 PM GMT (c6965d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/25/ae94e0a...c6965d7.html" title="Last updated on Oct 12, 2018, 9:24 PM GMT (c6965d7)">Diff</a>
> Dfn cleanup

- Gemfile.lock
- index.html
Fixes #5.
cc/ @eroux
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/26.html" title="Last updated on Oct 15, 2018, 6:12 PM GMT (4bc64a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/26/912017b...4bc64a3.html" title="Last updated on Oct 15, 2018, 6:12 PM GMT (4bc64a3)">Diff</a>
> Add note on asymmetry of reverse properties in frames.

- index.html
to use application/ld+json with required profile parameter.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/34.html" title="Last updated on Dec 28, 2018, 8:15 PM UTC (9fb74d8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/34/8464604...9fb74d8.html" title="Last updated on Dec 28, 2018, 8:15 PM UTC (9fb74d8)">Diff</a>
> Update IANA section

- Gemfile.lock
- index.html
borrowing from the Intro of the Syntax document.
Fixes #32.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/33.html" title="Last updated on Jan 4, 2019, 7:34 PM UTC (a1b8a0b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/33/63e4e99...a1b8a0b.html" title="Last updated on Jan 4, 2019, 7:34 PM UTC (a1b8a0b)">Diff</a>
> Improve the introduction

- Gemfile.lock
- Rakefile
- common/terms.html
- index.html
For #28.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/39.html" title="Last updated on Feb 21, 2019, 12:33 AM UTC (2a74f3f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/39/6fe17af...2a74f3f.html" title="Last updated on Feb 21, 2019, 12:33 AM UTC (2a74f3f)">Diff</a>
> Issue 28 media type

- index.html
* Remove `true` and `false` as values of `@embed`.
* Switch sentence order for Implicit Inclusion Flag.
* Add issue #41 marker for removing `@omitDefault`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/42.html" title="Last updated on Mar 13, 2019, 12:47 AM UTC (1af101d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/42/c663601...1af101d.html" title="Last updated on Mar 13, 2019, 12:47 AM UTC (1af101d)">Diff</a>
> Issue 36 editorial issues

- Gemfile.lock
- index.html
- tests/frame-manifest.jsonld
- tests/frame/0060-frame.jsonld
- tests/frame/0060-in.jsonld
- tests/frame/0060-out.jsonld
Depends on #42 being merged first.
Fixes #43.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/44.html" title="Last updated on Mar 13, 2019, 12:49 AM UTC (fcd66d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/44/8f754cc...fcd66d4.html" title="Last updated on Mar 13, 2019, 12:49 AM UTC (fcd66d4)">Diff</a>
> Issue 43 embed first

- index.html
- tests/README.md
- tests/frame-manifest.jsonld
- tests/frame/eo01-frame.jsonld
- tests/frame/eo01-in.jsonld
- tests/frame/eo01-out.jsonld
- tests/frame/eo02-frame.jsonld
- tests/frame/eo02-in.jsonld
- tests/frame/eo02-out.jsonld
Some pre-existing tests marked `json-ld-1.0` and new tests added. The `ordered` option is added to these tests to guarantee predictable results.
Fixes #43.
> Replace `@first` and `@last` with `@once.

- index.html
- tests/frame-manifest.jsonld
- tests/frame/ra01-frame.jsonld
- tests/frame/ra01-in.jsonld
- tests/frame/ra01-out.jsonld
- tests/frame/ra02-frame.jsonld
- tests/frame/ra02-in.jsonld
- tests/frame/ra02-out.jsonld
- tests/frame/ra03-frame.jsonld
- tests/frame/ra03-in.jsonld
- tests/frame/ra03-out.jsonld
… to match both properties, `@id`, and `@type`.
Fixes #40.
> Update frame matching and add tests for requireAll

- index.html
Just as in API document: added these classes for the sake of homogeneity. Also, in this document, the introduction was (implicitly) appearing as normative, which is probably not good.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/53.html" title="Last updated on May 24, 2019, 3:04 PM UTC (8e29045)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/53/41bb3e5...8e29045.html" title="Last updated on May 24, 2019, 3:04 PM UTC (8e29045)">Diff</a>
> added missing normative/informative class in intro

- Gemfile.lock
- common/extract-examples.rb
- common/terms.html
- index.html
Use type-scoped and property-scoped terms, and take advantage of "context definition" as the shape of a map used as a context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/59.html" title="Last updated on Jul 12, 2019, 11:00 PM UTC (9e556d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/59/1524e90...9e556d2.html" title="Last updated on Jul 12, 2019, 11:00 PM UTC (9e556d2)">Diff</a>
> Use updated term definitions.

- common/algorithm-terms.html
- common/terms.html
- index.html
* Term Updates for w3c/json-ld-syntax#85
* Fix WebIDL.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/60.html" title="Last updated on Jul 22, 2019, 5:24 PM UTC (54e4c85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/60/0ba7047...54e4c85.html" title="Last updated on Jul 22, 2019, 5:24 PM UTC (54e4c85)">Diff</a>
> Term updates

- common/jsonld.js
- common/terms.html
- index.html
- tests/frame-manifest.jsonld
- tests/frame/in01-frame.jsonld
- tests/frame/in01-in.jsonld
- tests/frame/in01-out.jsonld
- tests/frame/in02-frame.jsonld
- tests/frame/in02-in.jsonld
- tests/frame/in02-out.jsonld
- tests/frame/in03-frame.jsonld
- tests/frame/in03-in.jsonld
- tests/frame/in03-out.jsonld
For w3c/json-ld-syntax#19.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/61.html" title="Last updated on Aug 1, 2019, 12:12 AM UTC (7938622)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/61/637d626...7938622.html" title="Last updated on Aug 1, 2019, 12:12 AM UTC (7938622)">Diff</a>
> Text and tests for framing `@included`

- index.html
- tests/frame-manifest.jsonld
- tests/frame/0062-frame.jsonld
- tests/frame/0062-in.jsonld
- tests/frame/0062-out.jsonld
- tests/frame/0063-frame.jsonld
- tests/frame/0063-in.jsonld
- tests/frame/0063-out.jsonld
* Separate `@preserve` from `@null` processing.
* Add tests for `@null` as a default value.
Fixes #64
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/65.html" title="Last updated on Aug 18, 2019, 4:04 PM UTC (72ee9d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/65/0ecbc60...72ee9d2.html" title="Last updated on Aug 18, 2019, 4:04 PM UTC (72ee9d2)">Diff</a>
> Fix lost array with container: set

- tests/frame-manifest.jsonld
- tests/frame/g010-frame.jsonld
- tests/frame/g010-in.jsonld
- tests/frame/g010-out.jsonld
> Test case for credentials framing.

- common/algorithm-terms.html
- index.html
- tests/frame/g010-frame.jsonld
... defaulting to false, and set to true when recursing into node objects. Add tests to not add node at top level if embedded is false and it has already been serialized, and also use the check on `@embed: @never` to make that happen only when in an embedded node object.
Update test g010 to not use `@type` in framing.
For #27.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/66.html" title="Last updated on Aug 31, 2019, 10:56 PM UTC (bbf87ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/66/1aff7e8...bbf87ef.html" title="Last updated on Aug 31, 2019, 10:56 PM UTC (bbf87ef)">Diff</a>
> Update framing algorithm to use `embedded flag` in _framing state_

- index.html
Same as the other doc... eventually, need to covert `jsonldoptions` to the correct case form.
***
<a href="https://pr-preview.s3.amazonaws.com/marcoscaceres/json-ld-framing/pull/67.html" title="Last updated on Sep 7, 2019, 12:40 AM UTC (111394d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/67/92b1f36...marcoscaceres:111394d.html" title="Last updated on Sep 7, 2019, 12:40 AM UTC (111394d)">Diff</a>
> Fix ReSpec error

- common/terms.html
- index.html
- tests/README.md
- tests/frame-manifest.html
- tests/manifest.html
- tests/template.haml
For For w3c/json-ld-api#167.
Note, tests already exist with mismatched language tags.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/75.html" title="Last updated on Oct 14, 2019, 9:26 PM UTC (44f9bc0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/75/18bce59...44f9bc0.html" title="Last updated on Oct 14, 2019, 9:26 PM UTC (44f9bc0)">Diff</a>
> Ignore language case when framing

- tests/frame-manifest.html
- tests/manifest.html
- tests/template.haml
The links e.g. to manifest.jsonld were giving a 404, pointing to a file `json_file`,
It looks like the template was missing the necessary details to expand the variable json_file.
You can currently observe the behavior by clicking the `manifest.jsonld` links at the following.
* [json-ld-api-tests](https://w3c.github.io/json-ld-api/tests/)
* [json-framing-ld-tests](https://w3c.github.io/json-ld-framing/tests/)
> Fix expansion of link template variable json_file, regenerate html.

- Gemfile.lock
- index.html
- tests/frame-manifest.html
- tests/frame-manifest.jsonld
- tests/frame/0064-frame.jsonld
- tests/frame/0064-in.jsonld
- tests/frame/0064-out.jsonld
For #74.
Also requires changes to expand to allow a default object to be a value of `@type` when framing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/78.html" title="Last updated on Oct 21, 2019, 6:22 PM UTC (767bbb4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/78/02a0aef...767bbb4.html" title="Last updated on Oct 21, 2019, 6:22 PM UTC (767bbb4)">Diff</a>
> Text and tests for default values of `@type`.

- index.html
* Update gem version and rewrite examples to not use `@graph`.
* Add a number of new examples to illustrate features.
For #69.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/79.html" title="Last updated on Oct 29, 2019, 10:55 PM UTC (b4d6c84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/79/3942e66...b4d6c84.html" title="Last updated on Oct 29, 2019, 10:55 PM UTC (b4d6c84)">Diff</a>
> More examples

- tests/frame-manifest.html
- tests/frame-manifest.jsonld
Update `baseIri` from `https://w3c.github.io/json-ld-api/tests/` to `https://w3c.github.io/json-ld-framing/tests/`.
But I'm wondering: wouldn't it make sense to use `https://w3c.github.io/json-ld-framing/tests/frame-manifest.html` as the base IRI, so that if we concat `baseIri` and `@id` we'd get resolvable URLs like https://w3c.github.io/json-ld-framing/tests/frame-manifest.html#t0001?
(And the same for the individual manifests in json-ld-api/tests.)
> Update baseIri to json-ld-framing

- index.html
with reference to example 5, where the default `true` value is implied.
For #88.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/91.html" title="Last updated on Dec 23, 2019, 8:25 PM UTC (63a34f8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/91/e212af6...63a34f8.html" title="Last updated on Dec 23, 2019, 8:25 PM UTC (63a34f8)">Diff</a>
> Improve omit graph flag example discussion

- index.html
For issue #92.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/93.html" title="Last updated on Jan 8, 2020, 7:33 PM UTC (ffe77a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/93/8473bf4...ffe77a2.html" title="Last updated on Jan 8, 2020, 7:33 PM UTC (ffe77a2)">Diff</a>
> Consolodate duplicate How to read this document sections.

- ack-script/acknowledgements.html
- common/algorithm-terms.html
- index.html
This is in line with changes to Compaction and Expansion that moved code to the API algorithmic steps.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/94.html" title="Last updated on Jan 25, 2020, 10:29 PM UTC (21f2a1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/94/1382f5c...21f2a1a.html" title="Last updated on Jan 25, 2020, 10:29 PM UTC (21f2a1a)">Diff</a>
> Extract non-recursive parts of the framing algorithm into the API.

- common/algorithm-terms.html
- common/terms.html
- index.html
includes adding some of the compaction language from `compact()` into `frame()`.
For w3c/json-ld-api#383.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/96.html" title="Last updated on Feb 27, 2020, 6:16 PM UTC (fe9e349)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/96/c0fd1e5...fe9e349.html" title="Last updated on Feb 27, 2020, 6:16 PM UTC (fe9e349)">Diff</a>
> Update WebIDL along the lines done for the API documen

- index.html
@davidlehn was right, this serves no purpose. By doing the reclusive call with a copy of _framing state_ with an updated _graph name_, we effectively use the processors own call-frame stack.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/97.html" title="Last updated on Feb 28, 2020, 8:37 PM UTC (1f6f66a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/97/c72739d...1f6f66a.html" title="Last updated on Feb 28, 2020, 8:37 PM UTC (1f6f66a)">Diff</a>
> Removes _graph stack_ from _framing state_ as unnecessary.

- tests/frame-manifest.jsonld
- tests/frame/0065-frame.jsonld
- tests/frame/0065-in.jsonld
- tests/frame/0065-out.jsonld
- tests/frame/0066-frame.jsonld
- tests/frame/0066-in.jsonld
- tests/frame/0066-out.jsonld
- tests/frame/0067-frame.jsonld
- tests/frame/0067-in.jsonld
- tests/frame/0067-out.jsonld
I noticed a discrepancy between JSON-LD Playground and RDF Distiller regarding frame matching.
This PR adds 3 tests for frame matching on a specified value.
Fixes https://github.com/w3c/json-ld-framing/issues/99
Original issue here:
https://github.com/digitalbazaar/jsonld.js/issues/300
I created a fix for this in jsonld.js repo and the I'm hoping to commit the tests here.
> Tests for #99: Framing matches on specified value

- index.html
This silences ReSpec, and is probably better than just removing [Exposed] altogether.
Thanks to @hober for the advice.
Matches w3c/json-ld-api#500.
CC/ @swickr @iherman
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/108.html" title="Last updated on Jun 26, 2020, 9:23 PM UTC (9bf3593)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/108/361f84a...9bf3593.html" title="Last updated on Jun 26, 2020, 9:23 PM UTC (9bf3593)">Diff</a>
> Make a global JsonLd interface.

- index.html
The JSON-LD Framing API specification extends interfaces of the JSON-LD API but does not use the `partial` extension keyword, meaning that interfaces from both specs cannot be automatically merged into one.
The JSON-LD Framing API specification also re-defines interfaces that are already defined in the JSON-LD API for no apparent reason, which is bad practice as it creates two normative definitions of the same object.
This update makes the following changes to drop duplicate definitions and improve cross-reference links between the JSON-LD Framing API and the JSON-LD API:
- Dropped duplicate definition of `JsonLd` interface
- Defined `JsonLdProcessor` as `partial` (and dropped `constructor` member since it is already defined in the JSON-LD API)
- Dropped duplicate definitions of …
> Fix invalid Web IDL

- index.html
Change `@omitGraph` to `omitGraph` in comment to example 41.
Fixes #116.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/139.html" title="Last updated on Oct 26, 2022, 4:49 PM UTC (b323c9f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/139/a0eb400...b323c9f.html" title="Last updated on Oct 26, 2022, 4:49 PM UTC (b323c9f)">Diff</a>
> Fix omitgraph example

- tests/frame-manifest.html
- tests/frame-manifest.jsonld
- tests/frame/0069-frame.jsonld
- tests/frame/0069-in.jsonld
- tests/frame/0069-out.jsonld
As suggested in the issue #142, I've added a test collection to better define what is expected when framing over a `@json` field.
> Added tests for `@json` field testcase in framing

- index.html
rather than optinoal, and use "frame" instead of "framed".
For #132.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/pull/154.html" title="Last updated on Aug 23, 2023, 5:00 PM UTC (1c2bd7a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-framing/154/17b2e78...1c2bd7a.html" title="Last updated on Aug 23, 2023, 5:00 PM UTC (1c2bd7a)">Diff</a>
> Change IANA Considerations to make the profile parameter required
